### ISSUE TITLE
Focusing Link actions view by Tab works only for the first time

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-link#193]
It occurs on FF, Safari and Edge.
Works fine on Chrome.

## Steps to reproduce
1. Click on link element in editable, link actions view should appear attached to the link element
2. Press Tab to move focus to the actions view
3. Click Once again to the same link element to move focus again to editable
4. Press Tab to move focus to the actions view

## Expected result
Link actions view is focused

## Current result
Focus went somewhere

## Preview
![apr-24-2018 09-12-57](https://user-images.githubusercontent.com/1057056/39171785-1ec0eee2-47a0-11e8-9862-194142323355.gif)

## The reason
This is because `Link.actionsView.focusTracker` stays focused after the `actionsView` is removed from `ContextualBalloon`. DOM `blur` event is not fired at all.

So this condition works only for the first time becuase `this.actionsView.focusTracker.isFocused` stays as true.
https://github.com/ckeditor/ckeditor5-link/blob/82dc81e92c0e5c940c7d879453297271bd944b6e/src/linkui.js#L220

This is a browser issue because focused element that is removed from DOM should dispatch blur event:
- https://bugzilla.mozilla.org/show_bug.cgi?id=559561 (reported 8 years ago :D)
- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6274504/ (2 years)

So we need to find a workaround for this. It might be resetting `FT` after removing `actionsView` from `CT` (here:)
https://github.com/ckeditor/ckeditor5-link/blob/82dc81e92c0e5c940c7d879453297271bd944b6e/src/linkui.js#L362-L363

**Comment by oskarwrobel** [comment]
Reported 9 years ago https://bugzilla.mozilla.org/show_bug.cgi?id=559561.

**Comment by oskarwrobel** [comment]
I'm wondering what we can do with it. I don't believe this bug will be ever solved by the FF, Safari, and Edge. Maybe we should use `MutationObserver` in the `FocusTracker` to detect if a focused element has been removed?

**Comment by oskarwrobel** [comment]
https://github.com/ckeditor/ckeditor5/issues/1501#issuecomment-463538194
We should do the same to fix this issue. Move focus from the element before remove.

**Comment by oleq** [comment]
https://github.com/ckeditor/ckeditor5-link/pull/216 improved it but didn't fix entirely. There are still some paths that fail

![2019-02-18 12-44-47 2019-02-18 12_46_31](https://user-images.githubusercontent.com/1099479/52948946-3bdf6180-337b-11e9-814c-f3d228d20703.gif)
